/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complaintmanagementsystem;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mochamadtry
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        MenuAwal.setVisible(true);
        BuildLoad.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        MenuAwal = new javax.swing.JPanel();
        LogoAps = new javax.swing.JLabel();
        MulaiAps = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        BuildLoad = new javax.swing.JPanel();
        buildModel = new javax.swing.JButton();
        loadModel = new javax.swing.JButton();
        LogoAps1 = new javax.swing.JLabel();
        copyright1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        MenuAwal.setBackground(new java.awt.Color(204, 255, 255));
        MenuAwal.setMinimumSize(new java.awt.Dimension(960, 560));

        LogoAps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaintmanagementsystem/Logomakr_2blLJ1.png"))); // NOI18N

        MulaiAps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaintmanagementsystem/power-button(3).png"))); // NOI18N
        MulaiAps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MulaiApsMousePressed(evt);
            }
        });

        copyright.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        copyright.setText("Copyright PowerPuff Boy inc. @2016");

        javax.swing.GroupLayout MenuAwalLayout = new javax.swing.GroupLayout(MenuAwal);
        MenuAwal.setLayout(MenuAwalLayout);
        MenuAwalLayout.setHorizontalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAwalLayout.createSequentialGroup()
                .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuAwalLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(LogoAps))
                    .addGroup(MenuAwalLayout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addComponent(MulaiAps))
                    .addGroup(MenuAwalLayout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(copyright)))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        MenuAwalLayout.setVerticalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAwalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(LogoAps)
                .addGap(102, 102, 102)
                .addComponent(MulaiAps)
                .addGap(95, 95, 95)
                .addComponent(copyright)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jLayeredPane1.add(MenuAwal);

        BuildLoad.setBackground(new java.awt.Color(204, 255, 255));

        buildModel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buildModel.setText("BUILD MODEL");
        buildModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildModelActionPerformed(evt);
            }
        });

        loadModel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        loadModel.setText("LOAD MODEL");
        loadModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadModelActionPerformed(evt);
            }
        });

        LogoAps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaintmanagementsystem/Logomakr_2blLJ1.png"))); // NOI18N

        copyright1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        copyright1.setText("Copyright PowerPuff Boy inc. @2016");

        javax.swing.GroupLayout BuildLoadLayout = new javax.swing.GroupLayout(BuildLoad);
        BuildLoad.setLayout(BuildLoadLayout);
        BuildLoadLayout.setHorizontalGroup(
            BuildLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildLoadLayout.createSequentialGroup()
                .addGroup(BuildLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuildLoadLayout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addGroup(BuildLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(copyright1)
                            .addGroup(BuildLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loadModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buildModel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BuildLoadLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(LogoAps1)))
                .addContainerGap(656, Short.MAX_VALUE))
        );
        BuildLoadLayout.setVerticalGroup(
            BuildLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildLoadLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LogoAps1)
                .addGap(64, 64, 64)
                .addComponent(buildModel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(loadModel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(copyright1)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jLayeredPane1.add(BuildLoad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildModelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buildModelActionPerformed

    private void loadModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadModelActionPerformed
        // TODO add your handling code here:
        boolean finishproses = false; 
        ComplaintManagementSystem cms = new ComplaintManagementSystem();
        try {
            cms.loadModel();
            finishproses = true;
            System.out.println("lalal");
        } catch (Exception ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (finishproses){
            BuildLoad.setVisible(false);
            MenuAwal.setVisible(true);
        }
    }//GEN-LAST:event_loadModelActionPerformed

    private void MulaiApsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MulaiApsMousePressed
        // TODO add your handling code here:
        BuildLoad.setVisible(true);
        MenuAwal.setVisible(false);
        
        
    }//GEN-LAST:event_MulaiApsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuildLoad;
    private javax.swing.JLabel LogoAps;
    private javax.swing.JLabel LogoAps1;
    private javax.swing.JPanel MenuAwal;
    private javax.swing.JLabel MulaiAps;
    private javax.swing.JButton buildModel;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel copyright1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loadModel;
    // End of variables declaration//GEN-END:variables
}
